modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT License"

[[mods]]
modId = "agsink"
version = "${file.jarVersion}"
displayName = "AGSink"
logoFile = "sink.png"
authors = "AG6"

description = '''
A generic kitchen sink mod :)
'''